### ISSUE TITLE
error from nvme-cli missing

### ISSUE THREAD

**Issue by moozaad** [yast/yast-storage-ng#1343]
Version        : 4.6.11-1.1

If `nvme-cli` tools is missing, the partition just throws an error at launch. It would be nice if it requested to install it or it could be added as a package recommends.

![image](https://github.com/yast/yast-storage-ng/assets/7650192/67ff5cde-eca6-4fdc-827d-aee304adfa29)

**Comment by aschnell** [comment]
Why nvme-cli is missing I cannot say. But libstorage-ng does not report this correctly. With a fix I'll merge within the next hour YaST installs nvme-cli (for me).

**Comment by joseivanlopez** [comment]
> > Could you please attach your YaST logs to the bug report? See https://en.opensuse.org/openSUSE:Report_a_YaST_bug#Attachments_-_y2logs.2C_hwinfo_etc.
> 
> I'll see what I can do tomorrow.

Don't worry. The bug was already confirmed and fixed, see https://github.com/openSUSE/libstorage-ng/pull/936.

> For a nice user experience, I would expect the same as bootloader, where it auto installs packages it needs for the job at launch. At very least a suggest: in the spec to install. https://build.opensuse.org/package/view_file/YaST:Head/libstorage-ng/libstorage-ng.spec?expand=1

Yes, that is how it is supposed to work with the fix above.

Thanks!
