### ISSUE TITLE
 RFC: NG partitioning section elements

### ISSUE THREAD

**Issue by wfeldt** [yast/yast-storage-ng#385]
Currently there are two elements: `proposal` and `volumes`.

With these subelements in `proposal`:
- `lvm`
- `resize_windows`
- `windows_delete_mode`
- `linux_delete_mode`
- `other_delete_mode`
- `lvm_vg_strategy`
- `lvm_vg_size`

and a list of `volume` elements in `volumes` describing each volume.

This leaves 
- `proposal_settings_editable`
- `expert_partitioner_warning`
- `root_subvolume_read_only`
- `use_separate_multipath_module`

to be distributed.

IMHO `proposal_settings_editable` belongs to `proposal`,
`root_subvolume_read_only` could be put into `proposal` but should really
be a read-only flag in the "/"-volume.

Then this leaves only `expert_partitioner_warning` and `use_separate_multipath_module`
directly in `partitioning`?

Links:
- https://github.com/yast/yast-storage-ng/blob/master/doc/old_and_new_proposal.md
- https://github.com/yast/yast-installation-control/blob/master/control/control.rnc

**Comment by shundhammer** [comment]
This sounds reasonable to me.

While we are at cleaning up those storage-related settings, please let's make sure not to leave any old cruft behind. We now have a unique chance to do incompatible changes with SLE-15; it will be quite a while until we get the next chance to do something like this. Let's not waste this opportunity!

**Comment by jsrain** [comment]
On root_subvolume_read_only: I would not add it into a volume; it is something specific for just one of the volumes, otherwise someone comes with an idea to put it to /home filesystem...

**Comment by wfeldt** [comment]
BTW, `root_subvolume_read_only` is used here:

https://github.com/yast/yast-installation/blob/master/src/lib/installation/clients/umount_finish.rb#L411-L413

and `use_separate_multipath_module` here:

https://github.com/yast/yast-storage/blob/master/src/include/partitioning/ep-all.rb#L266-L270

**Comment by jsrain** [comment]
root_subvolume_read_only: Used for CaaSP; clearly handles only the root volume, that's why I would not allow to include it for any volume

use_separate_multipath_module: we still have both of the modules (multipath, multipath-simple) referenced in the system, therefore we should perhaps keep it now (we still have 6 more months to remove it)
