### ISSUE TITLE
Nasty typo in translated string "in invalid" must be "is invalid"

### ISSUE THREAD

**Issue by sriemer** [yast/yast-storage-ng#463]
https://github.com/yast/yast-storage-ng/blob/27656b8f1c75654d9be54b08ed9b0597692690c3/src/lib/y2partitioner/actions/controllers/lvm_vg.rb#L267

Here is the typo. Please change this to "is invalid".

Found while checking:
https://l10n.opensuse.org/translate/yast-storage/master/de/?type=untranslated

Please fix this. TIA

**Comment by sriemer** [comment]
The typo has been introduced by commit 02c83d1a829f8bd77f7c3bd93dc1b0e1a9ddd4cf.

**Comment by aschnell** [comment]
Thanks, fixed in https://github.com/yast/yast-storage-ng/pull/464.
