### ISSUE TITLE
EFI and "bios grub", when created, should try to follow root partition

### ISSUE THREAD

**Issue by luizluca** [yast/yast-storage-ng#826]
Hello,

While installing in a Leap15 machine with two empty disks, EFI or "bios grub" partitions are created without a deterministic rule. It is always the same for the same machine setup but with different machines, it fluctuated between sda/sdb, ssd/hdd, sata0/sata1, biggest/smaller devices. I couldn't identify how a device is picked for EFI/"Bios Grub". It still tries to use the same disk even after I swapped sda/sdb. Is it sorted by Disk ID instead?

When EFI/"Bios Grub" partition is missing, it would be nice to try to create it in the same device where 1) grub is installed, 2) /boot is (normally the root partition) 3) first disk (using device name: sda).

**Comment by ancorgs** [comment]
There ARE deterministic rules. They are created in the same disk that "/" is placed.

And for selecting the disk for "/" in the very first attempt (before the user has used the "Guided Setup" button) there are also deterministic rules. Oversimplifying that logic a bit: it tries in every possible disk (in alphabetical order) and stops when it finds a disk in which is possible to install.

Please, use bugzilla to provide concrete logs of any attempt that you believe uses a wrong logic for it.

**Comment by luizluca** [comment]
For reference: https://bugzilla.suse.com/show_bug.cgi?id=1124680
